GET  http://localhost:5000/details/

###

POST http://localhost:5000/details/
Content-Type: application/json

{
    "name":"Spider man homecomming",
    "img" :"https://lh3.googleusercontent.com/OGQkzkYdfhAXE6p-xufS_6mB3MtjDfPM6HZPdDrX5uJ09Dh1vzLZ6YflPIduh2Jk-h7H",
    "summary":"the several game marvel it was awesome movie"
}

###


PUT http://localhost:5000/detail/4/
Content-Type: application/json

{
    "name":"Escape Room",
    "img":"https://en.wikipedia.org/wiki/Escape_Room_%282019_film%29#/media/File:Escape_Room_(2019_poster).png",
    "summary" :"Escape Room was released in the United States on January 4, 2019, by Sony Pictures Entertainment, and grossed over $155 million worldwide."
}

###


DELETE http://localhost:5000/detail/4/